### ISSUE TITLE
License

### ISSUE THREAD

**Issue by olafghanizadeh** [trys/tomango-2018#24]
Hey Trys,

What sort of License do you have on this? I'm wondering to what degree I'm allowed to fork this and use some of the code as a basis for a Hugo boilerplate I'm going to use for client projects (not distributed).

**Comment by trys** [comment]
@olafghanizadeh Hey :wave: thanks for your message. The design & code is all owned by Tomango so we'd prefer for the code not to be used as a boilerplate. The repo is public to provide a look under the hood for those curious of the underlying code, so by all means take inspiration from it, but don't go overboard!

Hope that's alright :)
